services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama # Ollama Models and configs will be stored here
      - ./:/workspace
    working_dir: /workspace
    environment:
      - OLLAMA_HOST=0.0.0.0 # Allow Ollama to listen on host network
    restart: unless-stopped

volumes:
  ollama_data:
